spring:
  application:
    name: board03
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe  # DB?/??? ?? ??
    username: springghost                      # Oracle ??? ??
    password: 1234                             # ????

  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: /templates/
      suffix: .html

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.jang.gitminiprojectthejoeun.dto
  config-location: classpath:mybatis/config/config.xml

server:
  port: 8080