spring:
  application:
    name: gitminiprojectthejoeun
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springproject
    password: 1234

  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: /templates/
      suffix: .html

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.jang.gitminiprojectthejoeun.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080